version: '3'

services:
  admin:
    depends_on:
      - api
    environment:
      API_ENDPOINT: "admin.empilements.localhost; http://api.empilements.localhost/_/"
      CORS_ENABLED: "true"
    image: directus/app:7.0.18
    labels:
      traefik.frontend.rule: "Host:admin.empilements.localhost"
      traefik.port: "80"

  adminer:
    depends_on:
      - db
    image: adminer
    labels:
      traefik.frontend.rule: "Host:adminer.empilements.localhost"
      traefik.port: "8080"

  api:
    image: directus/api:2.0.18
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: "empilements"
      DATABASE_USERNAME: "root"
      DATABASE_PASSWORD: "root"
      ADMIN_EMAIL: "admin@empilements.localhost"
      ADMIN_PASSWORD: "admin"
    labels:
      traefik.frontend.rule: "Host:api.empilements.localhost"
      traefik.port: "80"
    volumes:
      - ./etc/api.php.ini:/etc/php7/conf.d/99_empilements.ini
      - ./src/public/var:/var/www/html/public/uploads/_/originals/var
      - ./etc/Thumbnailer.php:/var/www/html/src/core/Directus/Filesystem/Thumbnailer.php

  db:
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'
    environment:
      MYSQL_DATABASE: empilements
      MYSQL_ROOT_PASSWORD: root
    image: mysql:5.6
    volumes:
      - ./var/db:/var/lib/mysql
      - ./etc/empilements.sql:/docker-entrypoint-initdb.d/00_empilements.sql

  gatsbyjs:
    build:
      context: .
      dockerfile: gatsbyjs.Dockerfile
    command: ["develop", "--host=0.0.0.0"]
    entrypoint: ["fixuid", "gatsby"]
    image: constructionsincongrues/empilements/gatsbyjs
    labels:
      traefik.frontend.rule: "Host:gatsbyjs.empilements.localhost"
      traefik.port: "8000"
    volumes:
      - ./src/gatsbyjs:/usr/local/src

  php:
    build: .
    command: ["/bin/sh", "-c", "make configure && php -S 0.0.0.0:8000 -t public"]
    depends_on:
      - db
    image: constructionsincongrues/empilements/php
    labels:
      traefik.frontend.rule: "Host:empilements.localhost"
      traefik.port: "8000"
    volumes:
      - ./src:/usr/local/src
      - ./etc/${PROFILE-empilements.localhost}/.env:/usr/local/src/.env

  traefik:
    command: --api --docker
    image: traefik:1.7
    labels:
      traefik.frontend.rule: "Host:traefik.empilements.localhost"
      traefik.port: "8080"
    ports:
      - 80:80
    networks:
      default:
        aliases:
          - api.empilements.localhost
          - empilements.localhost
          - gatsbyjs.empilements.localhost
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
